# image to set env necessary to build custom plugins
# plugins:
#     usagetype

FROM ubuntu:22.04

ARG arg_working_dir

ENV working_dir="${arg_working_dir}"

USER root

RUN apt-get update

RUN apt-get -y install openjdk-11-jre-headless

WORKDIR "${working_dir}"

ENTRYPOINT [ "./build.bash" ]