# create logstash image with custom plugins installed

ARG ls_version

FROM docker.elastic.co/logstash/logstash:${ls_version}

ARG gid

RUN groupadd -g ${gid} reactome

COPY ./plugins/usagetype-plugin/logstash-filter-usage_type-0.0.1.gem /tmp/logstash-filter-usage_type-0.0.1.gem

COPY ./plugins/usagetype-plugin/logstash-filter-usage_type.gemspec /tmp/logstash-filter-usage_type.gemspec

RUN /usr/share/logstash/bin/logstash-plugin install --no-verify --local /tmp/logstash-filter-usage_type-0.0.1.gem
