filebeat.registry.file_permissions: 0640

filebeat.inputs:
- type: filestream
  id: default-filestream
  paths:
    - ingest/main/main_extended_log*
    - ingest/idg/idg_extended_log*
    - ingest/reactomews/*.txt
  close.reader.on_eof: true
  clean_removed: true

output.logstash:
  hosts: "${LOGSTASH_HOSTS}"
